version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "s3nh4s3cr3t4!!"
    ports:
      - "1433:1433"
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d